baseurl = "https://ricardoanderegg.com/"
DefaultContentLanguage = "en"
title = "rand[om]"
theme = "hugo-ink"
metaDataFormat = "yaml"
pygmentsstyle = "default"
# pygmentsUseClasses = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  title = "rand[om]"
  subtitle = "med ∩ ml"
  avatar = "https://ricardoanderegg.com/img/bike.jpg"
  favicon = true
  dateFormat = "January 2, 2006"
  featherIconsCDN = true
  mode = "auto"
  rss = true

  # favicon = "img/favicon.ico"
  # readingTime = true
  # useHLJS = true
  # social = true
  # hideAuthor = true

[Author]
  name = "Ricardo Ander-Egg"
  website = "ricardoanderegg.com"
  email = "ricardo.anderegg@gmail.com"
  github = "polyrand"
  gitlab = "polyrand"
  twitter = "ricardoanderegg"
  linkedin = "ricardoanderegg"
  telegram = "rick_dolphin"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Thoughts"
    url = "/thoughts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 3

[taxonomies]
  # category = "categories"
  tag = "tags"


[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/polyrand"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/ricardoanderegg/"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/ricardoanderegg"

[[params.social]]
  name = "Telegram"
  icon = "send"
  url = "https://t.me/polyrand"

[[params.social]]
  name = "Mail"
  icon = "mail"
  url = "mailto:ricardo.anderegg@gmail.com"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"