[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.65.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.65.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.65.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.65.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://rand.netlify.com/post/*"
  to = "https://ricardoanderegg.com/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rand.netlify.app/post/*"
  to = "https://ricardoanderegg.com/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ricardoanderegg.com/post/*"
  to = "https://ricardoanderegg.com/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rand.netlify.com/*"
  to = "https://ricardoanderegg.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rand.netlify.app/*"
  to = "https://ricardoanderegg.com/:splat"
  status = 301
  force = true  

# [[redirects]]
#   from = "/post/*"
#   to = "/posts/:splat"
